[package]
name = "potoo"
version = "0.0.0"
edition = "2021"
description = "The Cursed Editor for Bevy"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "2"
members = ["systems"]

[dependencies]
bevy = { version = "0.8.0" }
hot-lib-reloader = { version = "0.4.2", optional = true }
systems = { path = "systems" }

[features]
default = ["reload"]
reload = ["dep:hot-lib-reloader"]